tools:
  trivy:
    enabled: true
    patterns:
      - default
      - "package-lock.json"
      - "server/package-lock.json"
      - "package.json"
      - "server/package.json"
  eslint-8:
    enabled: true
  pmd-7:
    enabled: true
